### ISSUE TITLE
NP安卓12闪退

### ISSUE THREAD

**Issue by sunday123** [githubXiaowangzi/NP-Manager#1]
root的手机给了root权限，一打开滑了3个提示页面后，闪退

**Comment by wangyuan0217** [comment]
+1 android12 Redmi k30 Pro  root magisk 环境

**Comment by sunday123** [comment]
发现最新版本已经解决了

**Comment by wangyuan0217** [comment]
+1  一开始不闪退， 几天后，   再次打开就又闪退了，
还有 能给个语言设置的功能不，手机默认英文的，想改中文
