### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by SuperDuper77** [githubXiaowangzi/NP-Manager#20]
Having this issue the last 2days ago, it was fine with VPN. Now it wont work anymore, cant even use any protection/obfuscation function

**Comment by githubXiaowangzi** [comment]
Recently, the server has suffered a large number of CC attacks, and the access of IP in some regions has been blocked, and you can use the IP address of China, Malaysia or India to access.

**Comment by SuperDuper77** [comment]
Im from MY, still cant access

**Comment by githubXiaowangzi** [comment]
Contact me by email 2863678687@qq.com.   Tell  me your ip address and I add it to white list.
