### ISSUE TITLE
[Question] 为什么要检测代理？

### ISSUE THREAD

**Issue by cyb233** [githubXiaowangzi/NP-Manager#3]
理由是什么？这对全天候使用代理的用户很不友好

**Comment by zimixvx** [comment]
近平要检测你还要理由?

**Comment by cyb233** [comment]
> 近平要检测你还要理由?

技术疑问你扯政治是不是脑子有毛病，fork那么多外挂仓库不会还是个csgo挂狗吧？

**Comment by zimixvx** [comment]
呃呃，过毕设罢了，国内特有的喜欢查成分，蜘蛛急了?

**Comment by zimixvx** [comment]
蜘蛛差不多的了😓fork的比你那几个b java好多了

**Comment by cyb233** [comment]
比你没脑子扯政治好多了

**Comment by zimixvx** [comment]
你接着翻墙吧，墙国有你👍🏻

**Comment by cyb233** [comment]
咋，开着代理一定是翻墙是吧？游戏加速器和广告屏蔽服务不需要VPN服务了？你能多动动脑子不

**Comment by zimixvx** [comment]
这不就解决了，有可能的广告屏蔽服务以及vpn对广告展示的影响👍🏻，恭喜你解答了自己的问题，可以close了

**Comment by cyb233** [comment]
我寻思它没广告，理由不成立

**Comment by githubXiaowangzi** [comment]
新版本已经不闪退，改为只提示了
