### ISSUE TITLE
Doesn't work on Google pixel pro 7

### ISSUE THREAD

**Issue by Superman1974** [githubXiaowangzi/NP-Manager#8]
Only get blank screen on current np manager 3.0.74
![Screenshot_20230723-112905](https://github.com/githubXiaowangzi/NP-Manager/assets/43328637/f7352091-355e-4647-a297-2173589412a0)
![Screenshot_20230723-112922](https://github.com/githubXiaowangzi/NP-Manager/assets/43328637/c0e677b8-ee91-47ec-9688-5d4f3983f451)

**Comment by githubXiaowangzi** [comment]
断网后进入，再开网，因为广告sdk的影响开屏会白屏
