### ISSUE TITLE
Modex3.0 怎么配置自定义的签名，而不是用默认的签名

### ISSUE THREAD

**Issue by Lvbuqing** [githubXiaowangzi/NP-Manager#9]

**Comment by githubXiaowangzi** [comment]
点击apk文件-功能-Apk签名-生成签名

**Comment by Lvbuqing** [comment]
当前np版本号：3.0.74
测试流程：
1.生成好签名mykey放一边。
2.使用modex3.0处理
3.安装app
4.修改smali
5.点击apk文件-功能-Apk签名，签名秘钥：mykey，签名方案：与原app保持一致，确定
6.安装app，提示与安装的app签名不符
7.重新签名，点击apk文件-功能-Apk签名，签名秘钥：默认，签名方案：与原app保持一致，确定
8.安装成功
综上所述，modex3.0使用的是 默认签名，没有地方可以配置自定义的签名

**Comment by Lvbuqing** [comment]
使用我自己的签名重新签名一遍，不会导致modex去签名失效吧

**Comment by githubXiaowangzi** [comment]
不会，除非你modex-处理失败了

**Comment by Lvbuqing** [comment]
好的，感谢
